In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))
print(a)

[[[0.70852189 0.77683214 0.5418494  0.59322374 0.54704927]
  [0.09497167 0.25213626 0.17141824 0.22696471 0.48480225]
  [0.55463282 0.35753437 0.99910342 0.29764084 0.73199311]]

 [[0.29513432 0.98643736 0.38749134 0.10460269 0.19720489]
  [0.12135787 0.14967599 0.46423354 0.34949584 0.59674501]
  [0.50040947 0.41464989 0.07673999 0.59297652 0.35909008]]]


In [4]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?
# si tienen el mismo tamaño

print(a.size)
print(b.size)

30
30


In [6]:
#8. Are you able to add a and b? Why or why not?
# no se pueden sumar porque no tienen el mismo arreglo

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c

In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[0.70852189 0.77683214 0.5418494  0.59322374 0.54704927]
  [0.09497167 0.25213626 0.17141824 0.22696471 0.48480225]
  [0.55463282 0.35753437 0.99910342 0.29764084 0.73199311]]

 [[0.29513432 0.98643736 0.38749134 0.10460269 0.19720489]
  [0.12135787 0.14967599 0.46423354 0.34949584 0.59674501]
  [0.50040947 0.41464989 0.07673999 0.59297652 0.35909008]]]
[[[1.70852189 1.77683214 1.5418494  1.59322374 1.54704927]
  [1.09497167 1.25213626 1.17141824 1.22696471 1.48480225]
  [1.55463282 1.35753437 1.99910342 1.29764084 1.73199311]]

 [[1.29513432 1.98643736 1.38749134 1.10460269 1.19720489]
  [1.12135787 1.14967599 1.46423354 1.34949584 1.59674501]
  [1.50040947 1.41464989 1.07673999 1.59297652 1.35909008]]]


In [10]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [11]:
#13. Does e equal to a? Why or why not?
#son iguales, porque esta multiplicado por 1.
print(e)
print(a)

[[[0.70852189 0.77683214 0.5418494  0.59322374 0.54704927]
  [0.09497167 0.25213626 0.17141824 0.22696471 0.48480225]
  [0.55463282 0.35753437 0.99910342 0.29764084 0.73199311]]

 [[0.29513432 0.98643736 0.38749134 0.10460269 0.19720489]
  [0.12135787 0.14967599 0.46423354 0.34949584 0.59674501]
  [0.50040947 0.41464989 0.07673999 0.59297652 0.35909008]]]
[[[0.70852189 0.77683214 0.5418494  0.59322374 0.54704927]
  [0.09497167 0.25213626 0.17141824 0.22696471 0.48480225]
  [0.55463282 0.35753437 0.99910342 0.29764084 0.73199311]]

 [[0.29513432 0.98643736 0.38749134 0.10460269 0.19720489]
  [0.12135787 0.14967599 0.46423354 0.34949584 0.59674501]
  [0.50040947 0.41464989 0.07673999 0.59297652 0.35909008]]]


In [12]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print('el numero maximo es', d_max)
print('el numero minimo es', d_min)
print('la media es', d_mean)

el numero maximo es 1.9991034189168628
el numero minimo es 1.0767399869821412
la media es 1.4311639645990653


In [13]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2, 3, 5))
f

array([[[0.70852189, 0.77683214, 0.5418494 , 0.59322374, 0.54704927],
        [0.09497167, 0.25213626, 0.17141824, 0.22696471, 0.48480225],
        [0.55463282, 0.35753437, 0.99910342, 0.29764084, 0.73199311]],

       [[0.29513432, 0.98643736, 0.38749134, 0.10460269, 0.19720489],
        [0.12135787, 0.14967599, 0.46423354, 0.34949584, 0.59674501],
        [0.50040947, 0.41464989, 0.07673999, 0.59297652, 0.35909008]]])

In [17]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question

f = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]
f = np.array(f1)
f
#value > d_min < d_mean:
    #value > d_mean < d_max, print (75)
    #value == d_mean, print (50)
    #print (0)
    #print (100)

array([[[ 75,  75,  75,  75,  75],
        [ 25,  25,  25,  25,  75],
        [ 75,  25, 100,  25,  75]],

       [[ 25,  75,  25,  25,  25],
        [ 25,  25,  75,  25,  75],
        [ 75,  25,   0,  75,  25]]])